config/routes.rb
Rails.application.routes.draw do
  get 'pricelist/index'
  get 'retailer/index'
  get 'retailer/new'
  get 'retailer/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 # DC Routes start
 	get 'dc', 		to: "distribution_centers#index", as: 'dc'
 	get "dc/new", to: "distribution_centers#new", 	as: "new_dc"
 	post	"dc/create", to: "distribution_centers#create", as: "create_dc"

 # DC Routes End

 # PRODUCT Routes Star
 get 'products', to: "products#index", as: 'products'
 get 'product/new', to: "products#new", as: 'new_product'
 post 'product/create', to: "products#create", as: 'create_product'
 get 'product/:id', to: "products#edit", as: 'edit_product'
 patch 'product/:id', to: "products#update", as: 'update_product'
 get 'product/:id/delete', to: "products#delete", as: 'delete_product'
 # PRODUCT Routes End
 
 # Retailer
 get 'retailers', to: "retailer#index", as: "retailers"
 get 'retailer/new', to: "retailer#new", as: "new_retailer"
 post 'retailer/create', to: "retailer#create", as: "create_retailer"
 get 'retailer/:id/show', to: "retailer#show", as: "sho_rwetailer"
 get 'retailer/:id', to: "retailer#edit", as: "edit_retailer"
 patch 'retailer/:id', to: "retailer#update", as: "update_retailer"
 get 'retailer/:id/delete', to: "retailer#delete", as: "delete_retailer"
 # Retailer


 # Price List
 get 'pricelist', to: "pricelist#index", as: "pricelist"
 get 'pricelist/new', to: "pricelist#new", as: "new_price_list"
 post 'pricelist/create', to: "pricelist#create", as: "create_pricelist"
 # Price List
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
end

app/models/distribution_center.rb
class DistributionCenter < ApplicationRecord
	has_one_attached :image

	def self.active
		where(status: false)
	end
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_adjustment.rb
class OrderAdjustment < ApplicationRecord
end

app/models/order_crate.rb
class OrderCrate < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/order_return_item.rb
class OrderReturnItem < ApplicationRecord
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
	belongs_to :product
end

app/models/procurement.rb
class Procurement < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :pricelists
	has_one_attached :image


	@metrics = ['Kg', 'Nos']
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	has_one_attached :image
	after_create :set_code

	def set_code
		self.code = 'PCR' + "%06d" % ((Retailer.maximum(:id).to_i)+1)
		self.save
	end


end

app/models/sale_price.rb
class SalePrice < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/distribution_centers_controller.rb
class DistributionCentersController < ApplicationController
  def index
  	@dcList = DistributionCenter.all.active
  end

  def new
    @dc = DistributionCenter.new
  end

  def create
    @dc = DistributionCenter.new(dc_params)
    @dc.save
  end

  def edit
  end

  def delete
  end

  private

  def dc_params
    params.require(:dc).permit(:name, :code, :address, :city, :state, :country, :lat, :long)
  end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, :only => [:edit, :update, :delete]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created successfully"
      redirect_to products_path
    else
      flash[:danger] = "Failed to create product"
      render :new
    end
  end

  def edit
  end

  def update
   if  @product.update(product_params)
    flash[:success] = "Product updated"
    redirect_to products_path
   else
    flash[:danger] = "Failed to update retailer details"
    render :edit
   end
  end

  def delete
    if @product.delete
      flash[:success] = "Product deleted successfully"
      redirect_to products_path
    else
      flash[:danger] = "Failed to delete product"
      redirect_to products_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image)
  end

  def find_product
    @product = Product.find_by_id(params[:id])
  end

end

app/controllers/retailer_controller.rb
class RetailerController < ApplicationController
	before_action :find_retailer, :only => [:show, :edit, :update, :delete]
  
  def index
  	@retailers = Retailer.all
  end

  def new
  	@retailer = Retailer.new
  end

  def create
  	@retailer = Retailer.new(retailer_params)
  	puts retailer_params
  	if @retailer.save
  		flash[:success] = "Retailer created successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to create retailer"
  		render :new
  	end
  end

  def edit
  end

  def show
  end

  def update
  	if @retailer.update(retailer_params)
  		flash[:success] = "Retails details updated successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to updated retails details"
  		render :edit
  	end
  end

  def delete
  	if @retailer.update_attribute(:status, 1)
  		flash[:success] = "Retails deleted successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to delete retails"
  		redirect_to retailers_path
  	end
  end

  private

  def retailer_params
  	params.require(:retailer).permit(:name, :shop_name, :mobile, :alternate_mobile, 
  		:email, :address, :landmark, :city, :state, :pincode, :latitude, :longitude, :image)
  end

  def find_retailer
  	@retailer = Retailer.find_by_id(params[:id])
  end

  def code
  	'PCR' + "%06d" % ((Retailer.maximun(:id) || 0)+1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distribution_centers_helper.rb
module DistributionCentersHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/retailer_helper.rb
module RetailerHelper
end

app/views/distribution_centers/_form.html.erb
<div class="form-group">
	<%= f.label :name, "DC Name" %>
	<%= f.text_field :name, :class => "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :code, "Code" %>
  <%= f.text_field :code, :class => "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :address, "Address" %>
  <%= f.text_field :address, :class => "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :city, "City" %>
  <%= f.text_field :city, :class => "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :state, "State" %>
  <%= f.text_field :state, :class => "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :country, "Code" %>
  <%= f.text_field :country, :class => "form-control"  %>
</div>

	
<%= f.submit "Save", :class => "btn btn-primary"  %>
<%= link_to "Cancel", dc_path,  :class => "btn btn-danger" %>

app/views/distribution_centers/edit.html.erb
<h1>DistributionCenters#edit</h1>
<p>Find me in app/views/distribution_centers/edit.html.erb</p>

app/views/distribution_centers/index.html.erb
<div class="container">  
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div

app/views/distribution_centers/new.html.erb
 <div class="container">
  <%= form_for @dc, :url => create_dc_path do |f| %>
    <%= render "form", f: f %>
    <% end %>
</div>