config/routes.rb
Rails.application.routes.draw do
  get 'pricelist/index'
  get 'retailer/index'
  get 'retailer/new'
  get 'retailer/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 # DC Routes start
 	get 'dc', 		to: "distribution_centers#index", as: 'dc'
 	get "dc/new", to: "distribution_centers#new", 	as: "new_dc"
 	post	"dc/create", to: "distribution_centers#create", as: "create_dc"

 # DC Routes End

 # PRODUCT Routes Star
 get 'products', to: "products#index", as: 'products'
 get 'product/new', to: "products#new", as: 'new_product'
 post 'product/create', to: "products#create", as: 'create_product'
 get 'product/:id', to: "products#edit", as: 'edit_product'
 patch 'product/:id', to: "products#update", as: 'update_product'
 get 'product/:id/delete', to: "products#delete", as: 'delete_product'
 # PRODUCT Routes End
 
 # Retailer
 get 'retailers', to: "retailer#index", as: "retailers"
 get 'retailer/new', to: "retailer#new", as: "new_retailer"
 post 'retailer/create', to: "retailer#create", as: "create_retailer"
 get 'retailer/:id/show', to: "retailer#show", as: "sho_rwetailer"
 get 'retailer/:id', to: "retailer#edit", as: "edit_retailer"
 patch 'retailer/:id', to: "retailer#update", as: "update_retailer"
 get 'retailer/:id/delete', to: "retailer#delete", as: "delete_retailer"
 # Retailer


 # Price List
 get 'pricelist', to: "pricelist#index", as: "pricelist"
 get 'pricelist/new', to: "pricelist#new", as: "new_price_list"
 post 'pricelist/create', to: "pricelist#create", as: "create_pricelist"
 # Price List
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
end

app/models/distribution_center.rb
class DistributionCenter < ApplicationRecord
	has_one_attached :image

	def self.active
		where(status: false)
	end
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_adjustment.rb
class OrderAdjustment < ApplicationRecord
end

app/models/order_crate.rb
class OrderCrate < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/order_return_item.rb
class OrderReturnItem < ApplicationRecord
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
	belongs_to :product
end

app/models/procurement.rb
class Procurement < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :pricelists
	has_one_attached :image


	@metrics = ['Kg', 'Nos']
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	has_one_attached :image
	after_create :set_code

	def set_code
		self.code = 'PCR' + "%06d" % ((Retailer.maximum(:id).to_i)+1)
		self.save
	end


end

app/models/sale_price.rb
class SalePrice < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pricelist_controller.rb
class PricelistController < ApplicationController
  def index
  	@price_list = Pricelist.all
  end

  def new
  	@price_list = Pricelist.new
  end

  def create
  	debugger
  	price_params[:product_id]
  end

  private

  def price_params
  	params.required(:pricelist).permit(:date, product_id: [], available_quantity: [], sale_price: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, :only => [:edit, :update, :delete]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created successfully"
      redirect_to products_path
    else
      flash[:danger] = "Failed to create product"
      render :new
    end
  end

  def edit
  end

  def update
   if  @product.update(product_params)
    flash[:success] = "Product updated"
    redirect_to products_path
   else
    flash[:danger] = "Failed to update retailer details"
    render :edit
   end
  end

  def delete
    if @product.delete
      flash[:success] = "Product deleted successfully"
      redirect_to products_path
    else
      flash[:danger] = "Failed to delete product"
      redirect_to products_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image)
  end

  def find_product
    @product = Product.find_by_id(params[:id])
  end

end

app/controllers/retailer_controller.rb
class RetailerController < ApplicationController
	before_action :find_retailer, :only => [:show, :edit, :update, :delete]
  
  def index
  	@retailers = Retailer.all
  end

  def new
  	@retailer = Retailer.new
  end

  def create
  	@retailer = Retailer.new(retailer_params)
  	puts retailer_params
  	if @retailer.save
  		flash[:success] = "Retailer created successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to create retailer"
  		render :new
  	end
  end

  def edit
  end

  def show
  end

  def update
  	if @retailer.update(retailer_params)
  		flash[:success] = "Retails details updated successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to updated retails details"
  		render :edit
  	end
  end

  def delete
  	if @retailer.update_attribute(:status, 1)
  		flash[:success] = "Retails deleted successfully"
  		redirect_to retailers_path
  	else
  		flash[:danger] = "Failed to delete retails"
  		redirect_to retailers_path
  	end
  end

  private

  def retailer_params
  	params.require(:retailer).permit(:name, :shop_name, :mobile, :alternate_mobile, 
  		:email, :address, :landmark, :city, :state, :pincode, :latitude, :longitude, :image)
  end

  def find_retailer
  	@retailer = Retailer.find_by_id(params[:id])
  end

  def code
  	'PCR' + "%06d" % ((Retailer.maximun(:id) || 0)+1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/retailer_helper.rb
module RetailerHelper
end

app/views/pricelist/_form.html.erb
<div class="row">
	<div class="col col-md-2"></div>
	<div class="form-group col col-md-4">
		<%= f.text_field :product_id, multiple: true, :class => "form-control input"  %>
	</div>
	<div class="form-group col col-md-2">
		<%= f.text_field :available_quantity, multiple: true, :class => "form-control input"  %>
	</div>
	<div class="form-group col col-md-2">
		<%= f.text_field :sale_price, multiple: true, :class => "form-control input"  %>
	</div>
	<div class="col col-md-2"></div>
</div>

app/views/pricelist/index.html.erb
<h1>Pricelist#index</h1>
<p>Find me in app/views/pricelist/index.html.erb</p>
     

app/views/pricelist/new.html.erb
<%= form_for @price_list, :url => create_pricelist_path do |f| %>
	<div class="card mt-4 shadow p-3 mb-5 bg-white rounded">
		<div class="card-body">
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-4">
					<%= f.label :date, "Date" %>
				</div>
				<div class="col-md-4">
					<%= f.date_field :date, :class => "form-control input",  :value => Time.now.strftime('%Y-%m-%d'), 
					:min => Time.now.strftime('%Y-%m-%d')   %>
				</div>
				<div class="col-md-2"></div>
			</div>
		</div>
	</div>
	<div class="card mt-2 shadow p-3 mb-5 bg-white rounded overflow-hidden">
		<div class="card-body">
			<div class="row ">
				<div class="col-md-2"></div>
				<div class="col-md-4">Product</div>
				<div class="col-md-2">Available Qty</div>
				<div class="col-md-2">Price / Unit</div>
				<div class="col-md-2"></div>
			</div>
		  <% 10.times do %>
		 	  <%= render "form", f: f %>
		  <% end %>
		  <div class="row">
		  	<div class="col-md-2"></div>
		  	<div class="col-md-8">
		  		<%= f.submit "Save", :class => ""  %>
		  	</div>
		  	<div class="col-md-2"></div>
		  </div>
		</div>
	</div>
	
  
<% end %> 

app/views/products/_form.html.erb
<div class="form-group">
	<%= f.label :name, "Name" %>
	<%= f.text_field :name, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :metrics, "Metrics" %>
	<%= f.text_field :metrics, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :description, "Description" %>
	<%= f.text_area :description, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :image, "Image" %>
	<%= f.file_field :image, :class => "form-control"  %>
</div>
<%= f.submit "Save", :class => "btn btn-primary"  %>
<%= link_to "Cancel", products_path,  :class => "btn btn-danger" %>

app/views/products/edit.html.erb
<%= form_for @product, :url => update_product_path do |f| %>
<%= render "form", f: f %>
<% end %>
<%= @product.inspect %>

app/views/products/index.html.erb
<div class="row">
	<div class="col col-sm-12 col-md-12">
		<%= link_to "New", new_product_path, :class => "btn btn-primary float-right" %>
	</div>
</div>
<table class="table">
	<thead>
		<tr>
		<th>Image</th>
		<th>Name</th>
		<th>Metrics</th>
		<th>Description</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
		<% i = 1 %>
		<% @products.each do |product| %>
			<tr>
				<td><%= image_tag product.image.variant(resize_to_limit: [100, 100]) if product.image.attached? %></td>
				<td><%= product.name  %></td>
				<td><%= product.metrics  %></td>
				<td><%= product.description  %></td>
				<td><%= link_to fa_icon("pencil"), edit_product_path(product.id),  :class => "pencil" %> &nbsp;&nbsp; 
						<%= link_to fa_icon('trash'), delete_product_path(product.id), data: {confirm: "Are you sure, Delete #{product.name}?"}, :class => 'trash' %>
					</td>
			</tr>
			<% i += 1 %>
		<% end %>
	</tbody>
</table>

app/views/products/new.html.erb
<%= form_for @product, :url => create_product_path do |f| %>
	<%= render "form", f: f %>
<% end %>

app/views/retailer/_form.html.erb
<div class="form-group">
	<%= f.label :name, "Name" %>
	<%= f.text_field :name, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :shop_name, "Shop Name" %>
	<%= f.text_field :shop_name, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :mobile, "Mobile Number" %>
	<%= f.text_field :mobile, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :alternate_mobile, "Alternate Number" %>
	<%= f.text_field :alternate_mobile, :class => "form-control"  %>
</div>

<div class="form-group">
	<%= f.label :email, "Email" %>
	<%= f.text_field :email, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :address, "Address" %>
	<%= f.text_area :address, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :landmark, "Landmark" %>
	<%= f.text_field :landmark, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :pincode, "Zip Code" %>
	<%= f.text_field :pincode, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :latitude, "Latitude" %>
	<%= f.text_field :latitude, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :longitude, "Longitude" %>
	<%= f.text_field :longitude, :class => "form-control"  %>
</div>
<div class="form-group">
	<%= f.label :image, "Image" %>
	<%= f.file_field :image, :class => "form-control"  %>
</div>
<%= f.submit "Save", :class => "btn btn-primary"  %>
<%= link_to "Cancel", retailers_path,  :class => "btn btn-danger" %>

app/views/retailer/edit.html.erb
<%= form_for @retailer, :url => update_retailer_path do |f| %>
	<%= render "form", f: f %>
<% end %>

app/views/retailer/index.html.erb
<div class="row">
	<div class="col col-sm-12 col-md-12">
		<%= link_to "New", new_retailer_path, :class => "btn btn-primary float-right" %>
	</div>
</div>
<table class="table">
	<thead>
		<tr>
		<th>Sl No</th>
		<th>Code</th>
		<th>Name</th>
		<th>Shop Name</th>
		<th>Mobile</th>
		<th>Alternate Mobile</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
		<% i = 1 %>
		<% @retailers.each do |r| %>
			<tr>
				<td><%= i %></td>
				<td><%= r.code %></td>
				<td><%= r.name  %></td>
				<td><%= r.shop_name  %></td>
				<td><%= r.mobile  %></td>
				<td><%= r.alternate_mobile  %></td>
				<td>
					<%= link_to fa_icon("eye"), show_retailer_path(r.id),  :class => "eye" %> &nbsp;&nbsp; 
					<%= link_to fa_icon("pencil"), edit_retailer_path(r.id),  :class => "pencil" %> &nbsp;&nbsp; 
					<%= link_to fa_icon('trash'), delete_retailer_path(r.id), data: {confirm: "Are you sure, Delete #{r.code} - #{r.name}?"}, :class => 'trash' %>
					</td>
			</tr>
			<% i += 1 %>
		<% end %>
	</tbody>
</table>

app/views/retailer/new.html.erb
<%= form_for @retailer, :url => create_retailer_path do |f| %>
	<%= render "form", f: f %>
<% end %>

app/views/retailer/show.html.erb
show.html.erb